"""Work and study history: what the profile's CV sections read and write."""

from __future__ import annotations

import uuid
from datetime import date

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.schemas.common import ORMModel

#: The earliest year a CV entry may start. Anything before is a typo, and a
#: typo in a date is a CV an employer stops reading.
EARLIEST = date(1950, 1, 1)


class _Dated(BaseModel):
    # "  " is not an employer: blank after trimming fails `min_length`.
    model_config = ConfigDict(str_strip_whitespace=True)

    start_date: date | None = None
    #: Empty means "to the present".
    end_date: date | None = None

    @field_validator("start_date", "end_date")
    @classmethod
    def _month_in_range(cls, value: date | None) -> date | None:
        """Month-precise, kept as the first of the month, within sane years."""
        if value is None:
            return None
        value = value.replace(day=1)
        if value < EARLIEST:
            raise ValueError("date is too early")
        # A start next month is a job she has accepted; further out is a typo.
        if value.year > date.today().year + 1:
            raise ValueError("date is too far in the future")
        return value

    @model_validator(mode="after")
    def _ordered(self) -> _Dated:
        if self.start_date and self.end_date and self.end_date < self.start_date:
            raise ValueError("end_date is before start_date")
        return self


class WorkExperienceIn(_Dated):
    organization: str = Field(min_length=1, max_length=200)
    position: str = Field(min_length=1, max_length=160)
    location: str | None = Field(default=None, max_length=120)
    description: str | None = Field(default=None, max_length=2000)
    #: Generated by the browser once per form, so a retried save is one entry.
    client_ref: uuid.UUID | None = None


class WorkExperienceRead(ORMModel):
    id: uuid.UUID
    organization: str
    position: str
    location: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    description: str | None = None


class EducationIn(_Dated):
    institution: str = Field(min_length=1, max_length=200)
    degree: str | None = Field(default=None, max_length=40)
    field_of_study: str | None = Field(default=None, max_length=160)
    description: str | None = Field(default=None, max_length=2000)
    client_ref: uuid.UUID | None = None


class EducationRead(ORMModel):
    id: uuid.UUID
    institution: str
    degree: str | None = None
    field_of_study: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    description: str | None = None
