"""Diagnostic v2 schemas.

What the browser may send is narrow on purpose: which option she chose for
which question, and an id for the attempt. Scores, priorities and the user are
the server's to decide.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from app.core.constants import ScoreDimension
from app.schemas.recommendation import NextStep

Level = Literal[
    "starting_point", "building_foundation", "good_foundation", "strong_area", "advanced"
]


class DiagnosticOption(BaseModel):
    # The score is deliberately not sent: an answer is chosen for what it
    # says, not for what it is worth.
    id: str
    label_i18n: dict


class DiagnosticQuestion(BaseModel):
    id: uuid.UUID
    code: str
    # Null for the goals question, which measures no dimension.
    dimension: ScoreDimension | None
    type: Literal["single_choice", "routing", "goals"]
    order_index: int
    text_i18n: dict
    hint_i18n: dict | None = None
    max_choices: int = 1
    options: list[DiagnosticOption]


class DiagnosticQuestions(BaseModel):
    version: int
    questions: list[DiagnosticQuestion]


class DiagnosticAnswerIn(BaseModel):
    question_id: uuid.UUID
    option_ids: list[str] = Field(min_length=1, max_length=11)


class DiagnosticAttemptIn(BaseModel):
    # Generated by the browser when the run starts; repeats return the first.
    client_ref: uuid.UUID | None = None
    started_at: datetime | None = None
    answers: list[DiagnosticAnswerIn] = Field(min_length=1, max_length=60)


class DimensionResult(BaseModel):
    dimension: ScoreDimension
    # What this attempt measured, and where the dimension stands now — the
    # two differ once courses, tasks and applications have added to it.
    score: int = Field(ge=0, le=100)
    current: float | None = None
    level: Level


class PriorityRead(BaseModel):
    dimension: ScoreDimension
    priority: float
    need: float
    goal_match: float
    skill_gap: float
    urgency: float


class DiagnosticResult(BaseModel):
    attempt_id: uuid.UUID
    version: int
    completed_at: datetime | None
    is_baseline: bool
    overall: int = Field(ge=0, le=100)
    level: Level
    dimensions: list[DimensionResult]
    strongest: list[ScoreDimension]
    growth: list[PriorityRead]
    next_steps: list[NextStep]
    goals: list[str]
    family_focus: str | None = None


class DiagnosticHistoryItem(BaseModel):
    attempt_id: uuid.UUID
    version: int
    completed_at: datetime | None
    is_baseline: bool
    # Null for version-1 attempts, which did not keep what they measured.
    overall: int | None = None
    dimensions: dict[str, int] = {}
    goals: list[str] = []
