"""core schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-19 17:50:45.011893
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_questions",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "dimension",
            sa.Enum(
                "education_skills",
                "employment",
                "entrepreneurship",
                "financial_literacy",
                "healthy_lifestyle",
                "family_parenting",
                "social_activity",
                "international_integration",
                name="scoredimension",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=30), nullable=False),
        sa.Column("text_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_questions")),
    )
    op.create_index(
        "ix_assessment_questions_version_dimension",
        "assessment_questions",
        ["version", "dimension"],
        unique=False,
    )
    op.create_table(
        "opportunities",
        sa.Column(
            "source",
            sa.Enum(
                "edu_job",
                "invest_hub",
                "commerce",
                "internal",
                name="opportunitysource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "vacancy",
                "internship",
                "grant",
                "investment",
                "mentorship",
                "marketplace",
                "international_program",
                name="opportunitytype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organisation", sa.String(length=200), nullable=True),
        sa.Column("region", sa.String(length=60), nullable=True),
        sa.Column("required_skills", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("eligibility", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "reward",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Salary range, grant amount, etc.",
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("source", "external_id", name="uq_opportunities_source"),
    )
    op.create_index("ix_opportunities_deadline", "opportunities", ["deadline"], unique=False)
    op.create_index(op.f("ix_opportunities_region"), "opportunities", ["region"], unique=False)
    op.create_index(op.f("ix_opportunities_source"), "opportunities", ["source"], unique=False)
    op.create_index(
        "ix_opportunities_type_active", "opportunities", ["type", "is_active"], unique=False
    )
    op.create_table(
        "otp_challenges",
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("salt", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_challenges")),
    )
    op.create_index(
        "ix_otp_challenges_identifier_expires",
        "otp_challenges",
        ["identifier", "expires_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "suspended",
                "deleted",
                name="userstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum("uz", "ru", "en", name="language", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column(
            "region",
            sa.Enum(
                "tashkent_city",
                "tashkent_region",
                "andijan",
                "bukhara",
                "fergana",
                "jizzakh",
                "karakalpakstan",
                "kashkadarya",
                "khorezm",
                "namangan",
                "navoi",
                "samarkand",
                "sirdarya",
                "surkhandarya",
                name="region",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anonymised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_last_active_at", "users", ["last_active_at"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index(op.f("ix_users_region"), "users", ["region"], unique=False)
    op.create_index("ix_users_region_status", "users", ["region", "status"], unique=False)
    op.create_table(
        "ai_interactions",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "feature",
            sa.String(length=40),
            nullable=False,
            comment="navigator | roadmap | recommendation | content_assistant | risk_flag",
        ),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("trace_id", sa.String(length=80), nullable=False),
        sa.Column("prompt_excerpt", sa.Text(), nullable=True),
        sa.Column("response_excerpt", sa.Text(), nullable=True),
        sa.Column("retrieved_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("refused", sa.Boolean(), nullable=False),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_interactions_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_interactions")),
    )
    op.create_index(
        op.f("ix_ai_interactions_trace_id"), "ai_interactions", ["trace_id"], unique=False
    )
    op.create_index(
        "ix_ai_interactions_user_created",
        "ai_interactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_interactions_user_id"), "ai_interactions", ["user_id"], unique=False
    )
    op.create_table(
        "applications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "in_review",
                "accepted",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("external_application_id", sa.String(length=120), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_applications_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_applications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("user_id", "opportunity_id", name="uq_applications_user_id"),
    )
    op.create_index(
        op.f("ix_applications_opportunity_id"), "applications", ["opportunity_id"], unique=False
    )
    op.create_index(
        "ix_applications_status_submitted", "applications", ["status", "submitted_at"], unique=False
    )
    op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_baseline", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assessments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
    )
    op.create_index(
        "ix_assessments_user_completed", "assessments", ["user_id", "completed_at"], unique=False
    )
    op.create_index(op.f("ix_assessments_user_id"), "assessments", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=30), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=True),
        sa.Column(
            "classification",
            sa.Enum(
                "public",
                "internal",
                "personal",
                "sensitive",
                name="dataclassification",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("request_id", sa.String(length=60), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "consent_logs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "terms_of_use",
                "privacy_policy",
                "profile_analytics",
                "share_edu_job",
                "share_invest_hub",
                "share_commerce",
                "ai_personalisation",
                "marketing_communication",
                name="consentscope",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_consent_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_logs")),
    )
    op.create_index(op.f("ix_consent_logs_user_id"), "consent_logs", ["user_id"], unique=False)
    op.create_index(
        "ix_consent_logs_user_scope_created",
        "consent_logs",
        ["user_id", "scope", "created_at"],
        unique=False,
    )
    op.create_table(
        "development_plans",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "horizon",
            sa.Enum("3m", "6m", "12m", "36m", name="goalhorizon", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generated_by_ai", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("trace_id", sa.String(length=80), nullable=True),
        sa.Column("rationale", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_development_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_development_plans")),
    )
    op.create_index(
        op.f("ix_development_plans_user_id"), "development_plans", ["user_id"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "horizon",
            sa.Enum("3m", "6m", "12m", "36m", name="goalhorizon", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column(
            "dimension",
            sa.Enum(
                "education_skills",
                "employment",
                "entrepreneurship",
                "financial_literacy",
                "healthy_lifestyle",
                "family_parenting",
                "social_activity",
                "international_integration",
                name="scoredimension",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", name="priority", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("achieved", sa.Boolean(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "integration_events",
        sa.Column(
            "system",
            sa.Enum(
                "edu_job",
                "invest_hub",
                "commerce",
                name="integrationsystem",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "consent_scope",
            sa.String(length=40),
            nullable=True,
            comment="Consent scope that authorised this transfer",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "acknowledged",
                "failed",
                "dead_letter",
                name="integrationeventstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_integration_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_events")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_integration_events_idempotency_key")),
    )
    op.create_index(
        "ix_integration_events_status_next_retry",
        "integration_events",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        "ix_integration_events_system_created",
        "integration_events",
        ["system", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_events_user_id"), "integration_events", ["user_id"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "source_type",
            sa.String(length=40),
            nullable=False,
            comment="program | guideline | faq | legal | classifier | partner_catalog",
        ),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_knowledge_documents_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    op.create_table(
        "mentor_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("headline", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("expertise", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column("availability", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_mentees", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating_avg", sa.Float(), nullable=True),
        sa.Column("sessions_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mentor_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentor_profiles")),
    )
    op.create_index(op.f("ix_mentor_profiles_user_id"), "mentor_profiles", ["user_id"], unique=True)
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_end", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "in_app",
                "email",
                "sms",
                "push",
                name="notificationchannel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum(
                "onboarding_incomplete",
                "course_start",
                "deadline",
                "skill_gap",
                "progress",
                "inactivity",
                name="notificationtrigger",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_scheduled", "notifications", ["scheduled_for", "sent_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_notifications_user_read", "notifications", ["user_id", "read_at"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("age_group", sa.String(length=20), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("education_level", sa.String(length=60), nullable=True),
        sa.Column("education_field", sa.String(length=120), nullable=True),
        sa.Column("employment_status", sa.String(length=60), nullable=True),
        sa.Column("profession", sa.String(length=120), nullable=True),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column("marital_status", sa.String(length=40), nullable=True),
        sa.Column("children_count", sa.Integer(), nullable=True),
        sa.Column("has_disability", sa.Boolean(), nullable=True),
        sa.Column(
            "is_in_women_register",
            sa.Boolean(),
            nullable=True,
            comment="Listed in the state 'Ayollar daftari' register",
        ),
        sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("interests", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("completeness_percent", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "programs",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goal_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "vocational_skills",
                "ethics_culture",
                "health",
                "international",
                "parenting",
                "financial_literacy",
                "entrepreneurship",
                "leadership",
                "legal_literacy",
                "digital_safety",
                "mentorship_networking",
                "volunteering",
                name="programcategory",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum(
                "video",
                "text",
                "audio",
                "live",
                "offline",
                "blended",
                name="programformat",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum("uz", "ru", "en", name="language", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column("target_age_min", sa.Integer(), nullable=True),
        sa.Column("target_age_max", sa.Integer(), nullable=True),
        sa.Column("target_regions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("target_segments", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=True),
        sa.Column("duration_weeks", sa.Integer(), nullable=True),
        sa.Column("prerequisites", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("learning_outcomes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skills_taught", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("assessment_type", sa.String(length=40), nullable=True),
        sa.Column("has_certificate", sa.Boolean(), nullable=False),
        sa.Column("next_step", sa.String(length=120), nullable=True),
        sa.Column("provider", sa.String(length=200), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("cover_url", sa.String(length=500), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_programs_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
        sa.UniqueConstraint("slug", name=op.f("uq_programs_slug")),
    )
    op.create_index(op.f("ix_programs_category"), "programs", ["category"], unique=False)
    op.create_index(
        "ix_programs_category_published", "programs", ["category", "is_published"], unique=False
    )
    op.create_table(
        "risk_flags",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "flag_type",
            sa.Enum(
                "inactivity",
                "dropout_risk",
                "stalled_plan",
                "safety_escalation",
                name="riskflagtype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notified_coordinator_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notified_coordinator_id"],
            ["users.id"],
            name=op.f("fk_risk_flags_notified_coordinator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_risk_flags_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_flags")),
    )
    op.create_index(op.f("ix_risk_flags_user_id"), "risk_flags", ["user_id"], unique=False)
    op.create_index(
        "ix_risk_flags_user_resolved", "risk_flags", ["user_id", "resolved_at"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "mother",
                "mentor",
                "trainer",
                "regional_coordinator",
                "admin",
                "partner",
                "moderator",
                name="role",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "scope_region",
            sa.Enum(
                "tashkent_city",
                "tashkent_region",
                "andijan",
                "bukhara",
                "fergana",
                "jizzakh",
                "karakalpakstan",
                "kashkadarya",
                "khorezm",
                "namangan",
                "navoi",
                "samarkand",
                "sirdarya",
                "surkhandarya",
                name="region",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("granted_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["users.id"],
            name=op.f("fk_user_roles_granted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role", name="uq_user_roles_user_id"),
    )
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "assessment_answers",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("raw_answer", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_answers_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["assessment_questions.id"],
            name=op.f("fk_assessment_answers_question_id_assessment_questions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_answers")),
        sa.UniqueConstraint(
            "assessment_id", "question_id", name="uq_assessment_answers_assessment_id"
        ),
    )
    op.create_index(
        op.f("ix_assessment_answers_assessment_id"),
        "assessment_answers",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "development_scores",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=True),
        sa.Column(
            "dimension",
            sa.Enum(
                "education_skills",
                "employment",
                "entrepreneurship",
                "financial_literacy",
                "healthy_lifestyle",
                "family_parenting",
                "social_activity",
                "international_integration",
                name="scoredimension",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("baseline", sa.Float(), nullable=False),
        sa.Column("current", sa.Float(), nullable=False),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_development_scores_assessment_id_assessments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_development_scores_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_development_scores")),
    )
    op.create_index(
        "ix_development_scores_user_dimension",
        "development_scores",
        ["user_id", "dimension"],
        unique=False,
    )
    op.create_index(
        op.f("ix_development_scores_user_id"), "development_scores", ["user_id"], unique=False
    )
    op.create_table(
        "enrollments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "enrolled",
                "in_progress",
                "completed",
                "dropped",
                name="enrollmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("completed_modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_enrollments_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_enrollments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint("user_id", "program_id", name="uq_enrollments_user_id"),
    )
    op.create_index(op.f("ix_enrollments_program_id"), "enrollments", ["program_id"], unique=False)
    op.create_index(
        "ix_enrollments_status_started", "enrollments", ["status", "started_at"], unique=False
    )
    op.create_index(op.f("ix_enrollments_user_id"), "enrollments", ["user_id"], unique=False)
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_chunks_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_chunks_document_order",
        "knowledge_chunks",
        ["document_id", "chunk_index"],
        unique=False,
    )
    op.create_table(
        "mentor_sessions",
        sa.Column("mentor_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["mentor_profiles.id"],
            name=op.f("fk_mentor_sessions_mentor_id_mentor_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mentor_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentor_sessions")),
    )
    op.create_index(
        op.f("ix_mentor_sessions_mentor_id"), "mentor_sessions", ["mentor_id"], unique=False
    )
    op.create_index(
        op.f("ix_mentor_sessions_user_id"), "mentor_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "outcome_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "edu_job",
                "invest_hub",
                "commerce",
                "internal",
                name="opportunitysource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome_type",
            sa.String(length=40),
            nullable=False,
            comment="employment | business_registered | funding | first_sale | milestone",
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_outcome_records_application_id_applications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_outcome_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outcome_records")),
    )
    op.create_index(
        op.f("ix_outcome_records_user_id"), "outcome_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_outcome_records_user_type", "outcome_records", ["user_id", "outcome_type"], unique=False
    )
    op.create_table(
        "plan_items",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "dimension",
            sa.Enum(
                "education_skills",
                "employment",
                "entrepreneurship",
                "financial_literacy",
                "healthy_lifestyle",
                "family_parenting",
                "social_activity",
                "international_integration",
                name="scoredimension",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", name="priority", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_progress",
                "done",
                "skipped",
                name="planitemstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_plan_items_opportunity_id_opportunities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["development_plans.id"],
            name=op.f("fk_plan_items_plan_id_development_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_plan_items_program_id_programs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_items")),
    )
    op.create_index(op.f("ix_plan_items_plan_id"), "plan_items", ["plan_id"], unique=False)
    op.create_table(
        "program_modules",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("title_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_i18n", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_program_modules_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_modules")),
    )
    op.create_index(
        op.f("ix_program_modules_program_id"), "program_modules", ["program_id"], unique=False
    )
    op.create_table(
        "certificates",
        sa.Column("enrollment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.String(length=60), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("verification_code", sa.String(length=64), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_certificates_enrollment_id_enrollments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_certificates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("enrollment_id", name=op.f("uq_certificates_enrollment_id")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_certificates_serial_number")),
        sa.UniqueConstraint("verification_code", name=op.f("uq_certificates_verification_code")),
    )
    op.create_index(op.f("ix_certificates_user_id"), "certificates", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_certificates_user_id"), table_name="certificates")
    op.drop_table("certificates")
    op.drop_index(op.f("ix_program_modules_program_id"), table_name="program_modules")
    op.drop_table("program_modules")
    op.drop_index(op.f("ix_plan_items_plan_id"), table_name="plan_items")
    op.drop_table("plan_items")
    op.drop_index("ix_outcome_records_user_type", table_name="outcome_records")
    op.drop_index(op.f("ix_outcome_records_user_id"), table_name="outcome_records")
    op.drop_table("outcome_records")
    op.drop_index(op.f("ix_mentor_sessions_user_id"), table_name="mentor_sessions")
    op.drop_index(op.f("ix_mentor_sessions_mentor_id"), table_name="mentor_sessions")
    op.drop_table("mentor_sessions")
    op.drop_index("ix_knowledge_chunks_document_order", table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_document_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_enrollments_user_id"), table_name="enrollments")
    op.drop_index("ix_enrollments_status_started", table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_program_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_development_scores_user_id"), table_name="development_scores")
    op.drop_index("ix_development_scores_user_dimension", table_name="development_scores")
    op.drop_table("development_scores")
    op.drop_index(op.f("ix_assessment_answers_assessment_id"), table_name="assessment_answers")
    op.drop_table("assessment_answers")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index("ix_risk_flags_user_resolved", table_name="risk_flags")
    op.drop_index(op.f("ix_risk_flags_user_id"), table_name="risk_flags")
    op.drop_table("risk_flags")
    op.drop_index("ix_programs_category_published", table_name="programs")
    op.drop_index(op.f("ix_programs_category"), table_name="programs")
    op.drop_table("programs")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index("ix_notifications_scheduled", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_mentor_profiles_user_id"), table_name="mentor_profiles")
    op.drop_table("mentor_profiles")
    op.drop_table("knowledge_documents")
    op.drop_index(op.f("ix_integration_events_user_id"), table_name="integration_events")
    op.drop_index("ix_integration_events_system_created", table_name="integration_events")
    op.drop_index("ix_integration_events_status_next_retry", table_name="integration_events")
    op.drop_table("integration_events")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_development_plans_user_id"), table_name="development_plans")
    op.drop_table("development_plans")
    op.drop_index("ix_consent_logs_user_scope_created", table_name="consent_logs")
    op.drop_index(op.f("ix_consent_logs_user_id"), table_name="consent_logs")
    op.drop_table("consent_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_assessments_user_id"), table_name="assessments")
    op.drop_index("ix_assessments_user_completed", table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index("ix_applications_status_submitted", table_name="applications")
    op.drop_index(op.f("ix_applications_opportunity_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_ai_interactions_user_id"), table_name="ai_interactions")
    op.drop_index("ix_ai_interactions_user_created", table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_trace_id"), table_name="ai_interactions")
    op.drop_table("ai_interactions")
    op.drop_index("ix_users_region_status", table_name="users")
    op.drop_index(op.f("ix_users_region"), table_name="users")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index("ix_users_last_active_at", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_otp_challenges_identifier_expires", table_name="otp_challenges")
    op.drop_table("otp_challenges")
    op.drop_index("ix_opportunities_type_active", table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_source"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_region"), table_name="opportunities")
    op.drop_index("ix_opportunities_deadline", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_assessment_questions_version_dimension", table_name="assessment_questions")
    op.drop_table("assessment_questions")
    # ### end Alembic commands ###
