"""Portfolio: user-created projects, and whether her record is public.

Additive. One new table and four new columns on `profiles`, every one of them
defaulted so that each existing woman stays exactly as private as she was.

What is deliberately **not** here is an achievements table. An achievement is a
reading of a record the platform already holds — a completed enrollment, an
issued certificate, a passed evaluation, a partner-confirmed outcome — and
storing it a second time would make it possible for the two to disagree, or for
the same event to be awarded twice. `services.portfolio` derives them instead,
keyed by the source row, so a duplicate cannot be represented.

Revision ID: 0017
Revises: 0016
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "portfolio_projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.String(length=280), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        # Canonical slugs, checked against `skills` when written. A project form
        # never mints a new skill.
        sa.Column(
            "skill_slugs", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"
        ),
        sa.Column("project_url", sa.String(length=500), nullable=True),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("demo_url", sa.String(length=500), nullable=True),
        sa.Column("completed_on", sa.Date(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False, server_default=sa.false()),
        # Generated by the browser once per form, so a retried save is the same
        # project rather than a second one.
        sa.Column("client_ref", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_portfolio_projects_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_portfolio_projects"),
        sa.UniqueConstraint("user_id", "client_ref", name="uq_portfolio_projects_user_id"),
    )
    op.create_index("ix_portfolio_projects_user_id", "portfolio_projects", ["user_id"])

    # Every existing woman stays private: the default is false, and nothing
    # here publishes anybody.
    op.add_column(
        "profiles",
        sa.Column("portfolio_public", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("profiles", sa.Column("portfolio_slug", sa.String(length=40), nullable=True))
    op.add_column(
        "profiles",
        sa.Column("portfolio_published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "profiles",
        sa.Column(
            "portfolio_sections",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.create_unique_constraint("uq_profiles_portfolio_slug", "profiles", ["portfolio_slug"])


def downgrade() -> None:
    op.drop_constraint("uq_profiles_portfolio_slug", "profiles", type_="unique")
    op.drop_column("profiles", "portfolio_sections")
    op.drop_column("profiles", "portfolio_published_at")
    op.drop_column("profiles", "portfolio_slug")
    op.drop_column("profiles", "portfolio_public")

    op.drop_index("ix_portfolio_projects_user_id", table_name="portfolio_projects")
    op.drop_table("portfolio_projects")
