"""Module curricula for the demo catalogue.

The seed used to number modules — "Модуль 1", "Модуль 2" — and fill each with
the words "demo content". A catalogue that promises "цель, длительность,
измеримые результаты" and then lists six numbered blanks tells a woman nothing
about whether the course is the one she needs, which is the single decision the
page exists to help her make.

Each entry is `(uz, ru, en) title, (uz, ru, en) body, minutes`. Kept apart from
`seed.py` because it is content rather than logic, and content gets rewritten
by people who should not have to read a seeding script to do it.
"""

from __future__ import annotations

# (uz title, ru title, en title, uz body, ru body, en body, minutes)
Module = tuple[str, str, str, str, str, str, int]


def _m(uz: str, ru: str, en: str, uz_b: str, ru_b: str, en_b: str, minutes: int) -> Module:
    return (uz, ru, en, uz_b, ru_b, en_b, minutes)


MODULES: dict[str, list[Module]] = {
    "ai-va-raqamli-savodxonlik": [
        _m(
            "Sunʼiy intellekt nima va u qayerda ishlaydi",
            "Что такое ИИ и где он уже работает",
            "What AI is and where it already works",
            "Kundalik xizmatlardagi sunʼiy intellekt: qidiruv, tarjima, tavsiyalar.",
            "Искусственный интеллект в привычных сервисах: поиск, перевод, рекомендации.",
            "AI in the services you already use: search, translation, recommendations.",
            45,
        ),
        _m(
            "Yordamchiga qanday savol berish kerak",
            "Как формулировать запрос к ассистенту",
            "How to ask an assistant a question",
            "Aniq soʻrov tuzish: vazifa, kontekst va kutilayotgan natija.",
            "Точный запрос: задача, контекст и ожидаемый результат.",
            "A precise prompt: the task, the context and the result you expect.",
            60,
        ),
        _m(
            "Matn va tarjima",
            "Тексты и переводы",
            "Text and translation",
            "Xat, eʼlon va post yozish; oʻzbekcha-ruscha tarjimani tekshirish.",
            "Письма, объявления и посты; проверка узбекско-русского перевода.",
            "Letters, listings and posts; checking an Uzbek-Russian translation.",
            60,
        ),
        _m(
            "Jadval va hisob-kitob",
            "Таблицы и расчёты",
            "Spreadsheets and sums",
            "Formulalarni tushuntirish, xarajatlarni hisoblash, jadvalni tartibga solish.",
            "Объяснение формул, расчёт расходов, приведение таблицы в порядок.",
            "Explaining formulas, working out costs, tidying a spreadsheet.",
            45,
        ),
        _m(
            "Faktni tekshirish va ishonch chegarasi",
            "Проверка фактов и границы доверия",
            "Checking facts and the limits of trust",
            "Model xato qiladi: tibbiy, huquqiy va moliyaviy javoblarni tekshirish.",
            "Модель ошибается: как проверять медицинские, правовые и финансовые ответы.",
            "The model gets things wrong: how to check medical, legal and money answers.",
            45,
        ),
        _m(
            "Ishingizdagi uchta vazifa",
            "Три задачи из вашей работы",
            "Three tasks from your work",
            "Oʻz ishingizdan uchta vazifani tanlab, haftada sinab koʻrasiz.",
            "Выбираете три задачи из своей работы и пробуете их за неделю.",
            "Pick three tasks from your own work and try them over a week.",
            45,
        ),
    ],
    "ayol-rahbar": [
        _m(
            "Rahbar roli: nima oʻzgaradi",
            "Роль руководителя: что меняется",
            "The manager's role: what changes",
            "Ijrochidan rahbarga oʻtish va birinchi oydagi tipik xatolar.",
            "Переход от исполнителя к руководителю и типичные ошибки первого месяца.",
            "Moving from doing to leading, and the usual first-month mistakes.",
            45,
        ),
        _m(
            "Odam tanlash va moslashtirish",
            "Подбор и адаптация людей",
            "Hiring and settling people in",
            "Suhbat savollari, sinov muddati va birinchi hafta rejasi.",
            "Вопросы на собеседовании, испытательный срок и план первой недели.",
            "Interview questions, the trial period and a first-week plan.",
            60,
        ),
        _m(
            "Vazifa qoʻyish va teskari aloqa",
            "Постановка задач и обратная связь",
            "Setting tasks and giving feedback",
            "Vazifani tushunarli qilib qoʻyish va natijani ayblovsiz muhokama qilish.",
            "Как ставить задачу понятно и обсуждать результат без обвинений.",
            "Setting a task clearly and discussing the result without blame.",
            60,
        ),
        _m(
            "Qiyin suhbat",
            "Трудный разговор",
            "The difficult conversation",
            "Kechikish, sifat va nizolar haqida suhbat: tayyorgarlik va tuzilma.",
            "Разговор об опозданиях, качестве и конфликтах: подготовка и структура.",
            "Talking about lateness, quality and conflict: preparation and structure.",
            45,
        ),
        _m(
            "Byudjetsiz motivatsiya",
            "Мотивация без бюджета",
            "Motivation without a budget",
            "Tan olish, oʻsish va maʼnodan iborat motivatsiya vositalari.",
            "Признание, рост и смысл как инструменты мотивации.",
            "Recognition, growth and meaning as the tools you actually have.",
            45,
        ),
        _m(
            "Vakolat berish va oʻz vaqtingiz",
            "Делегирование и своё время",
            "Delegation and your own time",
            "Nimani berish mumkin, nimani yoʻq; rahbarning haftalik ritmi.",
            "Что можно передать, а что нельзя; недельный ритм руководителя.",
            "What can be handed over and what cannot; a manager's weekly rhythm.",
            45,
        ),
    ],
    "ayollar-salomatligi": [
        _m(
            "Yoshga qarab tekshiruv jadvali",
            "График осмотров по возрасту",
            "A check-up schedule by age",
            "Qaysi tekshiruvni qachon oʻtkazish kerak va nimaga eʼtibor berish lozim.",
            "Какие обследования и когда проходить, на что обращать внимание.",
            "Which check-ups to have when, and what to watch for.",
            60,
        ),
        _m(
            "Ovqatlanish va vitamin yetishmovchiligi",
            "Питание и дефициты",
            "Food and deficiencies",
            "Temir, D vitamini va yod: mintaqamizda keng tarqalgan yetishmovchiliklar.",
            "Железо, витамин D и йод: дефициты, распространённые в нашем регионе.",
            "Iron, vitamin D and iodine: the deficiencies common in this region.",
            45,
        ),
        _m(
            "Stress, uyqu va tiklanish",
            "Стресс, сон и восстановление",
            "Stress, sleep and recovery",
            "Charchoqning tanaga taʼsiri va kunlik tiklanish odatlari.",
            "Как усталость отражается на теле и какие ежедневные привычки помогают.",
            "How exhaustion shows up in the body, and the daily habits that help.",
            45,
        ),
    ],
    "bolaning-maktabga-tayyorgarligi": [
        _m(
            "«Maktabga tayyor» degani nima",
            "Что значит «готов к школе»",
            "What 'ready for school' means",
            "Bilim emas, balki eʼtibor, mustaqillik va muloqot koʻnikmalari.",
            "Не знания, а внимание, самостоятельность и умение общаться.",
            "Not knowledge but attention, independence and the ability to get along.",
            60,
        ),
        _m(
            "Kun tartibi va mustaqillik",
            "Режим дня и самостоятельность",
            "Daily routine and independence",
            "Uyqu, ovqat va yigʻilish: maktabgacha oʻrnatiladigan odatlar.",
            "Сон, еда и сборы: привычки, которые ставятся до школы.",
            "Sleep, meals and getting ready: habits to set before school starts.",
            45,
        ),
        _m(
            "Oʻrgatadigan oʻyinlar",
            "Игры, которые учат",
            "Games that teach",
            "Sanoq, harflar va mayda motorika uchun uydagi oddiy oʻyinlar.",
            "Простые домашние игры на счёт, буквы и мелкую моторику.",
            "Simple games at home for counting, letters and fine motor skills.",
            45,
        ),
    ],
    "buxgalteriya-asoslari": [
        _m(
            "Hisob tili: aktiv, passiv, kapital",
            "Язык учёта: активы, обязательства, капитал",
            "The language of accounts",
            "Balans nima uchun har doim tenglashadi va bu nimani anglatadi.",
            "Почему баланс всегда сходится и что это означает на практике.",
            "Why a balance sheet always balances, and what that means in practice.",
            60,
        ),
        _m(
            "Birlamchi hujjatlar",
            "Первичные документы",
            "Source documents",
            "Hisob-faktura, dalolatnoma, kassa orderi: nima uchun va qachon kerak.",
            "Счёт-фактура, акт, кассовый ордер: зачем нужны и когда оформляются.",
            "Invoices, acts and cash orders: what each is for and when it is issued.",
            60,
        ),
        _m(
            "Hisobvaraqlar rejasi va oʻtkazmalar",
            "План счетов и проводки",
            "The chart of accounts and entries",
            "Ikki tomonlama yozuv amalda: oddiy operatsiyalarni oʻtkazish.",
            "Двойная запись на практике: проводки простых операций.",
            "Double entry in practice: posting straightforward transactions.",
            60,
        ),
        _m(
            "1C bilan tanishuv",
            "Знакомство с 1С",
            "Getting started in 1C",
            "Bazani sozlash, kontragentlar va birinchi hujjatlarni kiritish.",
            "Настройка базы, справочники контрагентов и ввод первых документов.",
            "Setting up the database, counterparty lists and entering first documents.",
            60,
        ),
        _m(
            "Ish haqi va soliqlar",
            "Зарплата и налоги",
            "Payroll and tax",
            "Ish haqini hisoblash, ushlab qolishlar va ijtimoiy toʻlovlar.",
            "Начисление зарплаты, удержания и социальные платежи.",
            "Calculating pay, deductions and social contributions.",
            60,
        ),
        _m(
            "Hisobot va muddatlar",
            "Отчётность и сроки",
            "Reporting and deadlines",
            "Yillik taqvim: qaysi hisobot qachon topshiriladi.",
            "Годовой календарь: какой отчёт и когда сдаётся.",
            "The yearly calendar: which report is due when.",
            45,
        ),
    ],
    "emotsional-barqarorlik": [
        _m(
            "Charchash qanday koʻrinadi",
            "Как выглядит выгорание",
            "What burnout looks like",
            "Dam olish bilan oʻtmaydigan charchoq belgilarini tanib olish.",
            "Как распознать усталость, которая не проходит после отдыха.",
            "Recognising the exhaustion that rest no longer fixes.",
            45,
        ),
        _m(
            "Chegara: aybsiz «yoʻq» deyish",
            "Границы: сказать «нет» без вины",
            "Boundaries: saying no without guilt",
            "Munosabatni buzmasdan rad javobini berish iboralari.",
            "Формулировки отказа, которые не разрушают отношения.",
            "Ways to say no that do not damage the relationship.",
            45,
        ),
        _m(
            "Yordam soʻrash",
            "Просить о помощи",
            "Asking for help",
            "Kimga murojaat qilish mumkin va soʻrovni qanday aytish kerak.",
            "К кому можно обратиться и как сформулировать просьбу.",
            "Who you can turn to, and how to put the request.",
            45,
        ),
    ],
    "hunarmandchilik-biznesi": [
        _m(
            "Buyum tannarxi",
            "Себестоимость изделия",
            "What an item costs to make",
            "Material, vaqt va yashirin xarajatlarni hisoblash.",
            "Считаем материалы, своё время и скрытые расходы.",
            "Counting materials, your own hours and the costs you forget.",
            60,
        ),
        _m(
            "Narx va ustama",
            "Цена и наценка",
            "Price and margin",
            "Narx belgilash: zarar koʻrmasdan va xaridorni qoʻrqitmasdan.",
            "Как назначить цену, не работая в убыток и не отпугнув покупателя.",
            "Setting a price that neither loses money nor scares the buyer off.",
            45,
        ),
        _m(
            "Brend nomi va qadoq",
            "Название бренда и упаковка",
            "A brand name and packaging",
            "Nom tanlash, oddiy logotip va arzon qadoqlash yechimlari.",
            "Выбор имени, простой логотип и недорогая упаковка.",
            "Choosing a name, a simple mark and packaging that does not cost much.",
            45,
        ),
        _m(
            "Buyum surati",
            "Фотография изделия",
            "Photographing your work",
            "Telefonda tabiiy yorugʻlikda suratga olish va fonni tayyorlash.",
            "Съёмка на телефон при естественном свете и подготовка фона.",
            "Shooting on a phone in daylight, and preparing a background.",
            60,
        ),
        _m(
            "Sotuv kanallari",
            "Каналы продаж",
            "Where to sell",
            "Bozor, Telegram, Instagram va marketpleyslarni solishtirish.",
            "Сравнение рынка, Telegram, Instagram и маркетплейсов.",
            "Comparing the bazaar, Telegram, Instagram and the marketplaces.",
            60,
        ),
        _m(
            "Doimiy xaridorlar",
            "Постоянные покупатели",
            "Regular customers",
            "Buyurtmalar tarixi, takroriy sotuv va ogʻizdan ogʻizga tavsiya.",
            "История заказов, повторные продажи и рекомендации из уст в уста.",
            "Order history, repeat sales and word of mouth.",
            45,
        ),
    ],
    "huquqiy-savodxonlik": [
        _m(
            "Mehnat huquqlari",
            "Трудовые права",
            "Rights at work",
            "Shartnoma, taʼtil, dekret va ishdan boʻshatish tartibi.",
            "Договор, отпуск, декрет и порядок увольнения.",
            "Contracts, leave, maternity and how dismissal must work.",
            60,
        ),
        _m(
            "Oila huquqi",
            "Семейное право",
            "Family law",
            "Nikoh, mulk, aliment va bolalar huquqlari boʻyicha asoslar.",
            "Основы по браку, имуществу, алиментам и правам детей.",
            "The basics of marriage, property, maintenance and children's rights.",
            60,
        ),
        _m(
            "Tadbirkor huquqlari",
            "Права предпринимателя",
            "Rights as a business owner",
            "Roʻyxatdan oʻtish, tekshiruvlar va shartnoma tuzish qoidalari.",
            "Регистрация, проверки и правила заключения договоров.",
            "Registration, inspections and the rules for signing contracts.",
            60,
        ),
    ],
    "ingliz-tili-b1": [
        _m(
            "Hozirgi va oʻtgan zamon",
            "Настоящее и прошедшее время",
            "Present and past",
            "Kundalik hayot va tajriba haqida gapirish uchun asosiy zamonlar.",
            "Базовые времена для рассказа о повседневности и опыте.",
            "The core tenses for talking about your days and your experience.",
            90,
        ),
        _m(
            "Oʻzingiz va tajribangiz haqida",
            "Рассказ о себе и своём опыте",
            "Talking about yourself",
            "Ikki daqiqalik tanishtiruv: taʼlim, ish, koʻnikmalar.",
            "Двухминутный рассказ: образование, работа, навыки.",
            "A two-minute introduction: education, work, skills.",
            90,
        ),
        _m(
            "Kelasi zamon va rejalar",
            "Будущее и планы",
            "The future and plans",
            "Maqsad, reja va shartlar haqida gapirish.",
            "Как говорить о целях, планах и условиях.",
            "Talking about goals, plans and conditions.",
            90,
        ),
        _m(
            "Oʻqish: eʼlon, koʻrsatma, maqola",
            "Чтение: объявления, инструкции, статьи",
            "Reading: notices, instructions, articles",
            "Notanish soʻzlarga qaramasdan asosiy maʼnoni tushunish.",
            "Понимание основного смысла без разбора каждого незнакомого слова.",
            "Getting the sense without stopping at every unknown word.",
            90,
        ),
        _m(
            "Yozish: ariza va motivatsion xat",
            "Письмо: заявка и мотивационное письмо",
            "Writing: applications and motivation letters",
            "Xalqaro dastur va grantlarga ariza uchun tuzilma va iboralar.",
            "Структура и обороты для заявок на международные программы и гранты.",
            "Structure and phrasing for international programme and grant applications.",
            90,
        ),
        _m(
            "Suhbat: intervyu va taqdimot",
            "Разговор: интервью и презентация",
            "Speaking: interviews and presentations",
            "Savolga javob berish, aniqlashtirish va oʻz fikrini himoya qilish.",
            "Ответ на вопрос, уточнение и защита своей позиции.",
            "Answering, asking for clarification and defending a position.",
            90,
        ),
    ],
    "ingliz-tili-ish-uchun": [
        _m(
            "Ishchi xat",
            "Деловое письмо",
            "Business email",
            "Soʻrov, eslatma va rad javobi: tayyor tuzilmalar.",
            "Запрос, напоминание и вежливый отказ: готовые структуры.",
            "Requests, reminders and polite refusals: ready structures.",
            60,
        ),
        _m(
            "Telefon va qisqa uchrashuv",
            "Телефон и короткая встреча",
            "Calls and short meetings",
            "Tushunmaganda qayta soʻrash va kelishuvni yakunlash iboralari.",
            "Как переспросить, когда не поняли, и как закрепить договорённость.",
            "Asking someone to repeat, and closing on an agreement.",
            60,
        ),
        _m(
            "Kasbiy lugʻat",
            "Профессиональная лексика",
            "Vocabulary for your field",
            "Oʻz sohangiz uchun shaxsiy lugʻat toʻplash usuli.",
            "Способ собрать собственный словарь под свою сферу.",
            "A method for building your own vocabulary list for your field.",
            60,
        ),
        _m(
            "Rezyume va LinkedIn",
            "Резюме и LinkedIn на английском",
            "CV and LinkedIn in English",
            "Yutuqlarni raqamlar bilan koʻrsatuvchi iboralar.",
            "Формулировки, показывающие результат в цифрах.",
            "Phrasing that shows results as numbers.",
            60,
        ),
        _m(
            "Muzokara va aniqlashtirish",
            "Переговоры и уточнения",
            "Negotiating and clarifying",
            "Muddat, narx va shartlarni muhokama qilish.",
            "Обсуждение сроков, цены и условий.",
            "Discussing deadlines, price and terms.",
            60,
        ),
        _m(
            "Natija taqdimoti",
            "Презентация результата",
            "Presenting a result",
            "Uch daqiqalik hisobot: kontekst, natija, keyingi qadam.",
            "Трёхминутный отчёт: контекст, результат, следующий шаг.",
            "A three-minute report: context, result, next step.",
            60,
        ),
    ],
    "ish-suhbatiga-tayyorgarlik": [
        _m(
            "Bir sahifalik rezyume",
            "Резюме на одну страницу",
            "A one-page CV",
            "Tajribasi kam boʻlganda ham kuchli koʻrinadigan tuzilma.",
            "Структура, которая работает даже при небольшом опыте.",
            "A structure that works even when your experience is thin.",
            60,
        ),
        _m(
            "Portfolio va ish namunalari",
            "Портфолио и примеры работ",
            "A portfolio and work samples",
            "Nimani koʻrsatish mumkin, agar ish rasmiy boʻlmagan boʻlsa.",
            "Что показать, если работа была неофициальной или домашней.",
            "What to show when the work was informal or done at home.",
            45,
        ),
        _m(
            "Suhbat: savol va javoblar",
            "Собеседование: вопросы и ответы",
            "The interview: questions and answers",
            "Tanaffus, ish haqi va zaif tomonlar haqidagi savollar.",
            "Вопросы о перерыве в работе, зарплате и слабых сторонах.",
            "Questions about career gaps, salary and weaknesses.",
            60,
        ),
    ],
    "jamoatchilik-nutqi": [
        _m(
            "Sahna qoʻrquvi",
            "Страх сцены",
            "Stage fright",
            "Nutqdan oldin tanani va nafasni tinchlantirish usullari.",
            "Приёмы, которые успокаивают тело и дыхание перед выступлением.",
            "Techniques that settle the body and the breath before you speak.",
            45,
        ),
        _m(
            "Nutq tuzilmasi",
            "Структура речи",
            "Structuring a talk",
            "Boshlanish, uchta fikr va yakun: eslab qolinadigan sxema.",
            "Начало, три мысли и финал: схема, которая запоминается.",
            "An opening, three points and a close: a shape people remember.",
            45,
        ),
        _m(
            "Zal bilan ishlash",
            "Работа с аудиторией",
            "Working with the room",
            "Savollar, eʼtirozlar va eʼtiborni ushlab turish.",
            "Вопросы, возражения и удержание внимания.",
            "Questions, objections and holding attention.",
            45,
        ),
    ],
    "liderlik-va-notiqlik": [
        _m(
            "Maqsad va ustuvorliklar",
            "Цели и приоритеты",
            "Goals and priorities",
            "Yillik maqsadni haftalik qadamlarga boʻlish.",
            "Как разложить годовую цель на недельные шаги.",
            "Breaking a year's goal into weekly steps.",
            60,
        ),
        _m(
            "Vaqt va energiya",
            "Время и энергия",
            "Time and energy",
            "Ish, oila va oʻqishni bir haftada joylashtirish.",
            "Как уместить работу, семью и учёбу в одной неделе.",
            "Fitting work, family and study into one week.",
            45,
        ),
        _m(
            "Ommaviy nutq",
            "Публичная речь",
            "Speaking in public",
            "Qisqa nutq tayyorlash va uni mashq qilish.",
            "Подготовка короткого выступления и репетиция.",
            "Preparing a short talk, and rehearsing it.",
            60,
        ),
        _m(
            "Muzokara",
            "Переговоры",
            "Negotiation",
            "Oʻz manfaatini munosabatni buzmasdan himoya qilish.",
            "Как отстоять свой интерес, не разрушив отношения.",
            "Defending your interest without wrecking the relationship.",
            45,
        ),
    ],
    "mahalla-tashabbusi": [
        _m(
            "Muammoni topish",
            "Найти проблему",
            "Finding the problem",
            "Qoʻshnilar bilan suhbat va haqiqiy ehtiyojni aniqlash.",
            "Разговор с соседями и выявление настоящей потребности.",
            "Talking to neighbours and finding what is actually needed.",
            45,
        ),
        _m(
            "Jamoa yigʻish",
            "Собрать команду",
            "Gathering a team",
            "Kimni taklif qilish va vazifalarni qanday taqsimlash.",
            "Кого позвать и как распределить задачи.",
            "Who to ask, and how to split the work.",
            45,
        ),
        _m(
            "Reja va resurslar",
            "План и ресурсы",
            "A plan and resources",
            "Byudjet, muddat va hokimlik bilan muloqot.",
            "Бюджет, сроки и общение с хокимиятом.",
            "Budget, timings and dealing with the local administration.",
            60,
        ),
        _m(
            "Ishga tushirish va hisobot",
            "Запуск и отчёт",
            "Launch and report",
            "Natijani koʻrsatish va tashabbusni davom ettirish.",
            "Как показать результат и продолжить инициативу.",
            "Showing the result, and keeping the initiative going.",
            45,
        ),
    ],
    "mentorlik-asoslari": [
        _m(
            "Mentor kim",
            "Кто такой ментор",
            "What a mentor is",
            "Mentor, murabbiy va maslahatchi oʻrtasidagi farq.",
            "Разница между ментором, коучем и консультантом.",
            "The difference between a mentor, a coach and a consultant.",
            45,
        ),
        _m(
            "Uchrashuv tuzilmasi",
            "Структура встречи",
            "The shape of a session",
            "Bir soatlik uchrashuv: soʻrov, muhokama, kelishilgan qadam.",
            "Часовая встреча: запрос, обсуждение, согласованный шаг.",
            "An hour: the ask, the discussion, an agreed next step.",
            60,
        ),
        _m(
            "Chegara va odob",
            "Границы и этика",
            "Boundaries and ethics",
            "Maxfiylik, javobgarlik va nima mentorning ishi emasligi.",
            "Конфиденциальность, ответственность и что не входит в работу ментора.",
            "Confidentiality, responsibility, and what is not a mentor's job.",
            45,
        ),
        _m(
            "Natijani oʻlchash",
            "Измерение результата",
            "Measuring the result",
            "Uch oydan keyin nima oʻzgarganini qanday koʻrish mumkin.",
            "Как увидеть, что изменилось через три месяца.",
            "How to see what has changed after three months.",
            45,
        ),
    ],
    "mikrokredit-va-bank": [
        _m(
            "Kredit turlari va shartlari",
            "Виды кредитов и условия",
            "Loan types and terms",
            "Mikrokredit, imtiyozli kredit va lizing oʻrtasidagi farq.",
            "Разница между микрокредитом, льготным кредитом и лизингом.",
            "The difference between a microloan, a subsidised loan and leasing.",
            60,
        ),
        _m(
            "Shartnomani oʻqish",
            "Чтение договора",
            "Reading the contract",
            "Samarali stavka, jarima va yashirin toʻlovlarni topish.",
            "Как найти эффективную ставку, штрафы и скрытые платежи.",
            "Finding the effective rate, the penalties and the hidden fees.",
            60,
        ),
        _m(
            "Bank uchun biznes-reja",
            "Бизнес-план для банка",
            "A business plan for the bank",
            "Bank aslida nimaga qaraydi va qanday hujjat kerak.",
            "На что банк смотрит на самом деле и какой документ нужен.",
            "What the bank actually looks at, and what document it needs.",
            60,
        ),
        _m(
            "Murojaat va suhbat",
            "Обращение и переговоры",
            "Applying and negotiating",
            "Hujjatlar toʻplami va kredit mutaxassisi bilan suhbat.",
            "Пакет документов и разговор с кредитным специалистом.",
            "The document pack, and the conversation with the loan officer.",
            45,
        ),
    ],
    "moliyaviy-savodxonlik": [
        _m(
            "Pul qayerga ketadi",
            "Куда уходят деньги",
            "Where the money goes",
            "Bir oylik xarajatlarni yozib borish va tahlil qilish.",
            "Запись расходов за месяц и разбор результата.",
            "Tracking a month of spending, and reading what it shows.",
            60,
        ),
        _m(
            "Xavfsizlik yostigʻi",
            "Подушка безопасности",
            "An emergency fund",
            "Qancha yigʻish kerak va kichik daromadda qanday boshlash mumkin.",
            "Сколько копить и как начать при небольшом доходе.",
            "How much to save, and how to start on a small income.",
            45,
        ),
        _m(
            "Kredit madaniyati",
            "Культура кредита",
            "Borrowing sensibly",
            "Qachon kredit olish mumkin va qachon olmaslik kerak.",
            "Когда кредит уместен, а когда его лучше не брать.",
            "When a loan makes sense, and when it does not.",
            45,
        ),
        _m(
            "Firibgarlikdan himoya",
            "Защита от мошенничества",
            "Avoiding fraud",
            "Qoʻngʻiroq, SMS va «tez daromad» sxemalarining belgilari.",
            "Признаки звонков, SMS и схем «быстрого заработка».",
            "The signs of scam calls, texts and get-rich-quick schemes.",
            45,
        ),
    ],
    "oiladagi-muloqot": [
        _m(
            "Eshitish va tinglash",
            "Слушать и слышать",
            "Listening and hearing",
            "Suhbatdoshni toʻxtatmasdan eshitish va aniqlashtirish.",
            "Как выслушать, не перебивая, и уточнить услышанное.",
            "Hearing someone out without interrupting, and checking you understood.",
            45,
        ),
        _m(
            "Nizo buzmasdan",
            "Конфликт без разрушения",
            "Conflict without damage",
            "Ayblovdan oʻz his-tuygʻularini aytishga oʻtish.",
            "Переход от обвинения к разговору о своих чувствах.",
            "Moving from accusation to speaking about your own feelings.",
            45,
        ),
        _m(
            "Hurmat va chegara",
            "Уважение и границы",
            "Respect and boundaries",
            "Milliy qadriyatlarga tayangan holda kelishuvlar tuzish.",
            "Договорённости в семье с опорой на национальные ценности.",
            "Family agreements grounded in the values you already share.",
            45,
        ),
    ],
    "oilaviy-byudjet": [
        _m(
            "Daromad va xarajat hisobi",
            "Учёт доходов и расходов",
            "Tracking income and outgoings",
            "Daftar yoki ilova: har kuni yuritish mumkin boʻlgan usul.",
            "Тетрадь или приложение: способ, который реально вести каждый день.",
            "A notebook or an app: a method you will actually keep up.",
            60,
        ),
        _m(
            "Oyni rejalashtirish",
            "Планирование месяца",
            "Planning the month",
            "Majburiy toʻlovlar, oziq-ovqat va qolgan mablagʻ.",
            "Обязательные платежи, продукты и то, что остаётся.",
            "The fixed payments, the food, and what is left.",
            45,
        ),
        _m(
            "Jamgʻarma va maqsadlar",
            "Накопления и цели",
            "Saving towards something",
            "Aniq maqsad uchun yigʻish: toʻy, taʼmir, oʻqish.",
            "Накопление под конкретную цель: свадьба, ремонт, учёба.",
            "Saving for something specific: a wedding, repairs, tuition.",
            45,
        ),
        _m(
            "Qarzdan chiqish",
            "Выход из долгов",
            "Getting out of debt",
            "Qarzlarni tartiblash va toʻlash rejasini tuzish.",
            "Как упорядочить долги и составить план погашения.",
            "Putting debts in order, and building a repayment plan.",
            60,
        ),
    ],
    "onalar-maktabi": [
        _m(
            "Yosh davrlari",
            "Возрастные особенности",
            "What each age needs",
            "Uch, yetti va oʻn ikki yoshda nima oʻzgaradi.",
            "Что меняется в три, семь и двенадцать лет.",
            "What changes at three, at seven and at twelve.",
            60,
        ),
        _m(
            "Bola bilan suhbat",
            "Разговор с ребёнком",
            "Talking with your child",
            "Baqirmasdan eshitilish va ishonchni saqlash.",
            "Как быть услышанной без крика и сохранить доверие.",
            "Being heard without shouting, and keeping their trust.",
            60,
        ),
        _m(
            "Ekran va onlayn xavfsizlik",
            "Экраны и онлайн-безопасность",
            "Screens and staying safe online",
            "Vaqt chegarasi, kontent va notanish odamlar bilan muloqot.",
            "Ограничение времени, контент и общение с незнакомыми.",
            "Time limits, content, and contact with strangers.",
            60,
        ),
        _m(
            "Oʻzingizga gʻamxoʻrlik",
            "Забота о себе",
            "Looking after yourself",
            "Onaning charchogʻi butun oilaga taʼsir qiladi.",
            "Усталость матери отражается на всей семье.",
            "A mother's exhaustion reaches the whole family.",
            45,
        ),
    ],
    "onlayn-savdo-boshlash": [
        _m(
            "Tovar va maydonchani tanlash",
            "Выбор товара и площадки",
            "Choosing what to sell and where",
            "Nimani sotish mumkin va qaysi marketpleys mos keladi.",
            "Что можно продавать и какой маркетплейс подойдёт.",
            "What you can sell, and which marketplace suits it.",
            60,
        ),
        _m(
            "Doʻkonni roʻyxatdan oʻtkazish",
            "Регистрация магазина",
            "Registering the shop",
            "Hujjatlar, hisob raqami va sotuvchi kabineti.",
            "Документы, расчётный счёт и кабинет продавца.",
            "Documents, a bank account and the seller's dashboard.",
            45,
        ),
        _m(
            "Tovar kartochkasi",
            "Карточка товара",
            "The product listing",
            "Sarlavha, tavsif va xaridor izlaydigan soʻzlar.",
            "Заголовок, описание и слова, по которым ищет покупатель.",
            "The title, the description, and the words buyers search for.",
            60,
        ),
        _m(
            "Surat va tavsif",
            "Фото и описание",
            "Photos and copy",
            "Telefonda suratga olish va matnda eʼtirozlarga javob berish.",
            "Съёмка на телефон и ответы на возражения прямо в тексте.",
            "Shooting on a phone, and answering objections in the copy.",
            60,
        ),
        _m(
            "Birinchi sotuv va sharhlar",
            "Первая продажа и отзывы",
            "The first sale and reviews",
            "Yetkazib berish, qaytarish va birinchi sharhlarni yigʻish.",
            "Доставка, возвраты и сбор первых отзывов.",
            "Delivery, returns, and gathering those first reviews.",
            45,
        ),
    ],
    "raqamli-xavfsizlik": [
        _m(
            "Parol va ikki bosqichli kirish",
            "Пароли и двухфакторность",
            "Passwords and two-factor",
            "Kuchli parol, parol menejeri va SMS-kod.",
            "Надёжный пароль, менеджер паролей и SMS-код.",
            "A strong password, a password manager and the SMS code.",
            45,
        ),
        _m(
            "Fishing va firibgarlar",
            "Фишинг и мошенники",
            "Phishing and scammers",
            "Soxta havola, «bank xodimi» qoʻngʻirogʻi va pul soʻrash.",
            "Поддельные ссылки, звонок «сотрудника банка» и просьбы о деньгах.",
            "Fake links, the call from your 'bank', and requests for money.",
            45,
        ),
        _m(
            "Bolalar internetda",
            "Дети в интернете",
            "Children online",
            "Sozlamalar, ochiq suhbat va shubhali holatda nima qilish.",
            "Настройки, открытый разговор и что делать при подозрении.",
            "Settings, an open conversation, and what to do if something is wrong.",
            45,
        ),
    ],
    "smm-va-raqamli-marketing": [
        _m(
            "Auditoriya va pozitsiya",
            "Аудитория и позиционирование",
            "Your audience and your position",
            "Kim uchun yozayotganingizni aniqlash va farqni topish.",
            "Определить, для кого вы пишете, и найти отличие.",
            "Working out who you are writing for, and what sets you apart.",
            60,
        ),
        _m(
            "Kontent-reja",
            "Контент-план",
            "A content plan",
            "Bir oylik post rejasi: qanday qilib har kuni oʻylamaslik mumkin.",
            "План постов на месяц, чтобы не придумывать каждый день.",
            "A month of posts, so you are not inventing one every morning.",
            60,
        ),
        _m(
            "Telefonda suratga olish",
            "Съёмка на телефон",
            "Shooting on a phone",
            "Yorugʻlik, kadr va qisqa video uchun oddiy qoidalar.",
            "Свет, кадр и простые правила для короткого видео.",
            "Light, framing and simple rules for short video.",
            60,
        ),
        _m(
            "Matn va sarlavha",
            "Тексты и заголовки",
            "Copy and headlines",
            "Birinchi qator: nima uchun odam toʻxtaydi.",
            "Первая строка: почему человек останавливается.",
            "The first line: why anyone stops to read.",
            45,
        ),
        _m(
            "Reklama va raqamlar",
            "Реклама и цифры",
            "Ads and numbers",
            "Kichik byudjet, sinov va qaysi koʻrsatkichga qarash kerak.",
            "Небольшой бюджет, тест и на какие показатели смотреть.",
            "A small budget, a test, and which numbers matter.",
            60,
        ),
    ],
    "soglom-turmush": [
        _m(
            "Yoshga qarab profilaktika",
            "Профилактика по возрасту",
            "Prevention by age",
            "Qaysi tekshiruvlar va emlashlar zarur.",
            "Какие обследования и прививки нужны.",
            "Which screenings and vaccinations you need.",
            45,
        ),
        _m(
            "Kundalik ovqatlanish",
            "Питание каждый день",
            "Eating day to day",
            "Mahalliy mahsulotlardan muvozanatli ratsion tuzish.",
            "Сбалансированный рацион из доступных местных продуктов.",
            "A balanced diet built from what is actually in the market.",
            45,
        ),
        _m(
            "Sportzalsiz harakat",
            "Движение без спортзала",
            "Moving without a gym",
            "Uyda va yoʻlda bajarish mumkin boʻlgan mashqlar.",
            "Упражнения, которые можно делать дома и по дороге.",
            "Exercise you can do at home and on the way somewhere.",
            45,
        ),
        _m(
            "Uyqu va stress",
            "Сон и стресс",
            "Sleep and stress",
            "Uyquni tiklash va kunlik zoʻriqishni kamaytirish.",
            "Как восстановить сон и снизить ежедневное напряжение.",
            "Getting sleep back, and taking the edge off the day.",
            45,
        ),
    ],
    "tadbirkorlik-asoslari": [
        _m(
            "Gʻoya va mijoz muammosi",
            "Идея и проблема клиента",
            "The idea and the customer's problem",
            "Gʻoyani odamlar toʻlaydigan muammoga bogʻlash.",
            "Как связать идею с проблемой, за решение которой платят.",
            "Tying your idea to a problem someone will pay to have solved.",
            60,
        ),
        _m(
            "Biznes-model",
            "Бизнес-модель",
            "The business model",
            "Kim toʻlaydi, qancha va nima uchun: bir sahifada.",
            "Кто платит, сколько и за что — на одной странице.",
            "Who pays, how much and for what — on one page.",
            60,
        ),
        _m(
            "Narx va tannarx",
            "Цена и себестоимость",
            "Price and cost",
            "Har bir sotuvda daromad qoladigan narxni hisoblash.",
            "Расчёт цены, при которой на каждой продаже остаётся прибыль.",
            "Working out a price that leaves a profit on every sale.",
            60,
        ),
        _m(
            "Birinchi mijoz",
            "Первый клиент",
            "The first customer",
            "Reklamasiz birinchi sotuvni qanday qilish mumkin.",
            "Как сделать первую продажу без рекламы.",
            "Making the first sale without spending on advertising.",
            60,
        ),
        _m(
            "Biznesni roʻyxatdan oʻtkazish",
            "Регистрация бизнеса",
            "Registering the business",
            "YaTT yoki MChJ, hujjatlar va soliq rejimi.",
            "ИП или ООО, документы и налоговый режим.",
            "Sole trader or company, the paperwork and the tax regime.",
            60,
        ),
        _m(
            "Hisob va soliqlar",
            "Учёт и налоги",
            "Bookkeeping and tax",
            "Boshlangʻich hisob va muddatlarni oʻtkazib yubormaslik.",
            "Простой учёт и как не пропустить сроки.",
            "Simple bookkeeping, and not missing a deadline.",
            60,
        ),
    ],
    "tikuvchilik-va-dizayn": [
        _m(
            "Oʻlchov olish va oʻtirishi",
            "Мерки и посадка",
            "Measurements and fit",
            "Toʻgʻri oʻlchov olish va tayyor buyumning oʻtirishini tekshirish.",
            "Как снять мерки правильно и проверить посадку готового изделия.",
            "Taking measurements properly, and checking how the finished piece sits.",
            60,
        ),
        _m(
            "Mato va furnitura",
            "Ткани и фурнитура",
            "Fabric and trimmings",
            "Mato tanlash, sarfini hisoblash va bozorda xarid qilish.",
            "Выбор ткани, расчёт расхода и закупка на рынке.",
            "Choosing fabric, working out how much you need, and buying it.",
            60,
        ),
        _m(
            "Asosiy andaza",
            "Базовая выкройка",
            "The basic pattern",
            "Koʻylak andazasini qurish va oʻzingizga moslashtirish.",
            "Построение базовой выкройки платья и подгонка под себя.",
            "Drafting a basic dress pattern and adjusting it to a body.",
            60,
        ),
        _m(
            "Milliy bichim",
            "Национальный крой",
            "Traditional cut",
            "Atlas va adras bilan ishlash, anʼanaviy shakllar.",
            "Работа с атласом и адрасом, традиционные формы.",
            "Working with atlas and adras, and the traditional shapes.",
            60,
        ),
        _m(
            "Pardoz va sifat",
            "Отделка и качество",
            "Finishing and quality",
            "Chok, jiyak va buyumni sotuvga tayyorlash.",
            "Швы, обработка края и подготовка изделия к продаже.",
            "Seams, edges, and getting a piece ready to sell.",
            60,
        ),
        _m(
            "Kichik sex",
            "Небольшой цех",
            "A small workshop",
            "Ish joyi, buyurtmalar va yordamchi bilan ishlash.",
            "Рабочее место, поток заказов и работа с помощницей.",
            "The workspace, the flow of orders, and working with an assistant.",
            60,
        ),
    ],
}
